version: '3.1'
services:
  horse-info-crawler:
    container_name: horse_info_crawler
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.flake8:/var/app/.flake8
      - ./tests:/var/app/tests
      - ./main.py:/var/app/main.py
      - ./horse_info_crawler:/var/app/horse_info_crawler
    ports:
      - 8000:8000
    environment:
      TZ: Asia/Tokyo
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      RAW_DATA_BUCKET_NAME: local-raw-data
      PROCESSED_DATA_BUCKET_NAME: local-processed-data
      RACE_INFO_CRAWLED_DATA_BASE_DIR: race_info
      S3_ENDPOINT_URL: http://localstack:4566
    tty: true
    links:
      - localstack

  localstack:
    image: localstack/localstack:0.11.5
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=ap-northeast-1
    volumes:
      - ./localstack:/docker-entrypoint-initaws.d
    ports:
      - 4566:4566